-- ===========================================================
-- 1. CREATE DATABASE & SCHEMAS
-- ===========================================================

CREATE OR REPLACE DATABASE DEMO_CDC_DB;
USE DATABASE DEMO_CDC_DB;

CREATE OR REPLACE SCHEMA RAW;
CREATE OR REPLACE SCHEMA EDW;
CREATE OR REPLACE SCHEMA CONTROL;

-- ===========================================================
-- 2. CREATE RAW SOURCE TABLES
-- ===========================================================

CREATE OR REPLACE TABLE RAW.CUSTOMER_RAW (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    LOAD_TIMESTAMP TIMESTAMP
);
--SHOW TABLES IN SCHEMA RAW;

--DESCRIBE TABLE RAW.CUSTOMER_RAW;
--insert data automatically
CREATE OR REPLACE TABLE RAW.CUSTOMER_RAW AS
SELECT
    SEQ4() + 1 AS CUSTOMER_ID,
    'Customer_' || (SEQ4() + 1) AS CUSTOMER_NAME,
    'customer' || (SEQ4() + 1) || '@email.com' AS EMAIL,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 50000));

---Tran data----
CREATE OR REPLACE TABLE RAW.TRANSACTION_RAW (
    TRANSACTION_ID NUMBER,
    CUSTOMER_ID NUMBER,
    AMOUNT NUMBER(10,2),
    TRANS_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP
    
);
-- Initial Insert
---Insert data----
CREATE OR REPLACE TABLE RAW.TRANSACTION_RAW AS
SELECT
    SEQ4() + 1 AS TRANSACTION_ID,
    UNIFORM(1, 50000, RANDOM()) AS CUSTOMER_ID, -- random customer
    UNIFORM(10, 2000, RANDOM())::NUMBER(10,2) AS AMOUNT,
    DATEADD(
        day, 
        UNIFORM(-365, 0, RANDOM()), 
        CURRENT_DATE()
    ) AS TRANS_DATE,
    CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
FROM TABLE(GENERATOR(ROWCOUNT => 200000));


-- ===========================================================
-- 3. CREATE STREAMS FOR CDC TRACKING
-- ===========================================================

CREATE OR REPLACE STREAM RAW.CUSTOMER_STREAM
ON TABLE RAW.CUSTOMER_RAW
APPEND_ONLY = FALSE;


select * from RAW.CUSTOMER_STREAM order by customer_id asc;

SHOW STREAMS IN SCHEMA RAW;


CREATE STREAM RAW.CUSTOMER_STREAM
ON TABLE RAW.CUSTOMER_RAW
APPEND_ONLY = FALSE;


CREATE STREAM RAW.TRANSACTION_STREAM
ON TABLE RAW.TRANSACTION_RAW
APPEND_ONLY = FALSE;

-- ===========================================================
-- 4. CREATE TARGET SCD TYPE 2 TABLES
-- ===========================================================
CREATE OR REPLACE TABLE EDW.CUST_TRANS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    TRANSACTION_ID NUMBER,
    AMOUNT NUMBER(10,2),
    TRANS_DATE DATE,
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    IS_CURRENT BOOLEAN
);
--INITIAL LOAD INTO SCD2 TABLE (one-time only) 
--Initial Full Load into EDW.CUST_TRANS (Customer + Transactions)
--This loads the base state BEFORE CDC begins.
INSERT INTO EDW.CUST_TRANS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    TRANSACTION_ID,
    AMOUNT,
    TRANS_DATE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
)
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.EMAIL,
    t.TRANSACTION_ID,
    t.AMOUNT,
    t.TRANS_DATE,
    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    NULL AS EFFECTIVE_TO,
    TRUE AS IS_CURRENT
FROM RAW.CUSTOMER_RAW c
LEFT JOIN RAW.TRANSACTION_RAW t
    ON c.CUSTOMER_ID = t.CUSTOMER_ID;

----
INSERT INTO RAW.CUSTOMER_RAW
SELECT
    MAX(CUSTOMER_ID) + SEQ4() + 1,
    'NewCustomer_' || (SEQ4() + 1),
    'new' || (SEQ4() + 1) || '@gmail.com',
    CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT => 500));

UPDATE RAW.CUSTOMER_RAW
SET EMAIL = 'updated_' || EMAIL
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM RAW.CUSTOMER_RAW
    ORDER BY RANDOM()
    LIMIT 2000
);

DELETE FROM RAW.CUSTOMER_RAW
WHERE CUSTOMER_ID IN (
    SELECT CUSTOMER_ID
    FROM RAW.CUSTOMER_RAW
    ORDER BY RANDOM()
    LIMIT 500
);

---Create Warehouse for Tasks---
CREATE OR REPLACE WAREHOUSE ETL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE TASK CONTROL.CUST_TRANS_CDC_TASK
WAREHOUSE = ETL_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.CUSTOMER_STREAM')
  OR SYSTEM$STREAM_HAS_DATA('RAW.TRANSACTION_STREAM')
AS
MERGE INTO EDW.CUST_TRANS tgt
USING (
    SELECT
        c.CUSTOMER_ID,
        c.CUSTOMER_NAME,
        c.EMAIL,
        c.METADATA$ACTION AS CUST_ACTION,
        c.METADATA$ISUPDATE AS CUST_UPDATE,

        t.TRANSACTION_ID,
        t.AMOUNT,
        t.TRANS_DATE,
        t.METADATA$ACTION AS TRANS_ACTION,
        t.METADATA$ISUPDATE AS TRANS_UPDATE,

        GREATEST(c.LOAD_TIMESTAMP, t.LOAD_TIMESTAMP) AS LOAD_TS
    FROM RAW.CUSTOMER_STREAM c
    LEFT OUTER JOIN RAW.TRANSACTION_STREAM t
    ON c.CUSTOMER_ID = t.CUSTOMER_ID
) src
ON tgt.TRANSACTION_ID = src.TRANSACTION_ID
AND tgt.IS_CURRENT = TRUE

-- 1. SCD2 Update: close previous version
WHEN MATCHED AND (src.CUST_UPDATE = TRUE OR src.TRANS_UPDATE = TRUE) THEN
    UPDATE SET
        tgt.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        tgt.IS_CURRENT = FALSE

-- 2. Delete handling
WHEN MATCHED AND (src.CUST_ACTION = 'DELETE' OR src.TRANS_ACTION = 'DELETE') THEN
    UPDATE SET
        tgt.EFFECTIVE_TO = CURRENT_TIMESTAMP(),
        tgt.IS_CURRENT = FALSE

-- 3. Insert new SCD2 records
WHEN NOT MATCHED THEN
    INSERT (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        EMAIL,
        TRANSACTION_ID,
        AMOUNT,
        TRANS_DATE,
        EFFECTIVE_FROM,
        EFFECTIVE_TO,
        IS_CURRENT
    )
    VALUES (
        src.CUSTOMER_ID,
        src.CUSTOMER_NAME,
        src.EMAIL,
        src.TRANSACTION_ID,
        src.AMOUNT,
        src.TRANS_DATE,
        CURRENT_TIMESTAMP(),
        NULL,
        TRUE
    );

   ALTER TASK CONTROL.CUST_TRANS_CDC_TASK RESUME;

 

SELECT *
FROM EDW.CUST_TRANS
ORDER BY CUSTOMER_ID, TRANSACTION_ID, EFFECTIVE_FROM;



